stitch: ReportRipperStandalone.o stitch.cpp
	g++ --std=c++11 -o stitch stitch.cpp ReportRipperStandalone.o

ReportRipperStandalone.o: ReportRipperStandalone.cpp 
	g++ --std=c++11 -c ReportRipperStandalone.cpp

clean: 
	rm *.o stitch
